import type { ConversionTemplate } from "../conversion-templates";

/** Built-in 17-task PMP exam readiness bundle (dependency DAG + certification labels). */
export const pmpRegistrationSprintTemplate: ConversionTemplate = {
  id: "pmp_registration_sprint",
  name: "PMP Registration Sprint",
  conversionType: "project_plan",
  items: [
    {
      key: "confirm_eligibility",
      activity: "Confirm PMP eligibility (experience + education requirements)",
      classification: "Certification",
      startOffsetDays: 0,
      durationMinutes: 180,
    },
    {
      key: "pmi_account",
      activity: "Create or recover PMI.org account and complete profile",
      classification: "Certification",
      startOffsetDays: 1,
      durationMinutes: 90,
      dependsOnKeys: ["confirm_eligibility"],
    },
    {
      key: "document_hours",
      activity: "Document project leadership hours and supporting references",
      classification: "Certification",
      startOffsetDays: 2,
      durationMinutes: 360,
      dependsOnKeys: ["pmi_account"],
    },
    {
      key: "submit_application",
      activity: "Submit PMP application for PMI review",
      classification: "Certification",
      startOffsetDays: 4,
      durationMinutes: 240,
      dependsOnKeys: ["document_hours"],
    },
    {
      key: "pay_fee",
      activity: "Pay PMP exam fee and obtain eligibility ID",
      classification: "Certification",
      startOffsetDays: 6,
      durationMinutes: 60,
      dependsOnKeys: ["submit_application"],
    },
    {
      key: "training_35h",
      activity: "Complete 35 contact hours (PDU) training",
      notes: "Structured training aligned to the current ECO.",
      classification: "Certification",
      startOffsetDays: 7,
      durationMinutes: 2100,
      dependsOnKeys: ["pay_fee"],
    },
    {
      key: "schedule_vue",
      activity: "Schedule exam appointment with Pearson VUE",
      classification: "Certification",
      startOffsetDays: 8,
      durationMinutes: 90,
      dependsOnKeys: ["pay_fee"],
    },
    {
      key: "read_pmbok_agile",
      activity: "Read PMBOK guide + Agile Practice Guide sections",
      classification: "Certification",
      startOffsetDays: 10,
      durationMinutes: 1200,
      dependsOnKeys: ["training_35h"],
    },
    {
      key: "first_practice_exam",
      activity: "First full-length practice exam + log gaps",
      classification: "Certification",
      startOffsetDays: 18,
      durationMinutes: 240,
      dependsOnKeys: ["read_pmbok_agile"],
    },
    {
      key: "remediate_gaps",
      activity: "Remediate weakest domains from first practice exam",
      classification: "Certification",
      startOffsetDays: 20,
      durationMinutes: 480,
      dependsOnKeys: ["first_practice_exam"],
    },
    {
      key: "second_practice_exam",
      activity: "Second full-length practice exam under timed conditions",
      classification: "Certification",
      startOffsetDays: 24,
      durationMinutes: 240,
      dependsOnKeys: ["remediate_gaps"],
    },
    {
      key: "exam_day_logistics",
      activity: "Confirm exam center logistics, ID requirements, and arrival time",
      classification: "Certification",
      startOffsetDays: 26,
      durationMinutes: 120,
      dependsOnKeys: ["schedule_vue", "second_practice_exam"],
    },
    {
      key: "final_review",
      activity: "Final condensed review of formulas, agile themes, and code of ethics",
      classification: "Certification",
      startOffsetDays: 28,
      durationMinutes: 360,
      dependsOnKeys: ["second_practice_exam"],
    },
    {
      key: "audit_buffer",
      activity: "If selected for audit: assemble and submit audit evidence package",
      classification: "Certification",
      startOffsetDays: 12,
      durationMinutes: 300,
      dependsOnKeys: ["submit_application"],
      deadlineType: "audit-risk",
    },
    {
      key: "stakeholder_notify",
      activity: "Notify manager/mentor of exam date and coverage plan",
      classification: "Certification",
      startOffsetDays: 9,
      durationMinutes: 45,
      dependsOnKeys: ["schedule_vue"],
    },
    {
      key: "rest_and_logistics",
      activity: "Light review only: pack IDs, sleep plan, and travel buffer",
      classification: "Certification",
      startOffsetDays: 32,
      durationMinutes: 120,
      dependsOnKeys: ["exam_day_logistics", "final_review"],
    },
    {
      key: "sit_pmp_exam",
      activity: "Sit for the PMP certification exam",
      classification: "Certification",
      startOffsetDays: 34,
      durationMinutes: 240,
      dependsOnKeys: ["rest_and_logistics"],
      milestone: true,
      deadlineType: "exam",
    },
  ],
};
