import PDFDocument from "pdfkit";
import type { Task } from "@shared/schema";

const COLORS = {
  primary: "#1e40af",
  darkText: "#1f2937",
  mediumText: "#4b5563",
  lightText: "#9ca3af",
  border: "#d1d5db",
  checkboxBorder: "#6b7280",
  headerBg: "#eff6ff",
  priorityHighest: "#dc2626",
  priorityHigh: "#ea580c",
  priorityMedium: "#ca8a04",
  priorityLow: "#16a34a",
  priorityLowest: "#6b7280",
};

function getPriorityColor(priority: string): string {
  switch (priority?.toLowerCase()) {
    case "highest": return COLORS.priorityHighest;
    case "high": return COLORS.priorityHigh;
    case "medium-high": return COLORS.priorityMedium;
    case "medium": return COLORS.priorityMedium;
    case "low": return COLORS.priorityLow;
    case "lowest": return COLORS.priorityLowest;
    default: return COLORS.mediumText;
  }
}

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr + "T00:00:00");
    return d.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  } catch {
    return dateStr;
  }
}

export function generateChecklistPDF(tasks: Task[], date: string, userName?: string): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `AxTask Daily Checklist - ${date}`,
      Author: userName || "AxTask",
      Subject: "Daily Task Checklist",
    },
  });

  const pageWidth = 612 - 100;

  doc.font("Helvetica-Bold").fontSize(22).fillColor(COLORS.primary)
    .text("AxTask Daily Checklist", 50, 50, { align: "center", width: pageWidth });

  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(12).fillColor(COLORS.mediumText)
    .text(formatDate(date), { align: "center", width: pageWidth });

  if (userName) {
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor(COLORS.lightText)
      .text(`Prepared for: ${userName}`, { align: "center", width: pageWidth });
  }

  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor(COLORS.border).lineWidth(1).stroke();
  doc.moveDown(0.5);

  const sorted = [...tasks].sort((a, b) => {
    const statusOrder: Record<string, number> = { "pending": 0, "in-progress": 1, "completed": 2 };
    const sa = statusOrder[a.status] ?? 0;
    const sb = statusOrder[b.status] ?? 0;
    if (sa !== sb) return sa - sb;
    return (b.priorityScore || 0) - (a.priorityScore || 0);
  });

  const pendingTasks = sorted.filter(t => t.status !== "completed");
  const completedTasks = sorted.filter(t => t.status === "completed");

  let taskNumber = 0;

  if (pendingTasks.length > 0) {
    doc.font("Helvetica-Bold").fontSize(14).fillColor(COLORS.darkText)
      .text(`To Do (${pendingTasks.length} tasks)`, 50);
    doc.moveDown(0.3);

    for (const task of pendingTasks) {
      taskNumber++;
      drawTaskRow(doc, task, taskNumber, pageWidth, false);
    }
  }

  if (completedTasks.length > 0) {
    doc.moveDown(0.5);
    doc.font("Helvetica-Bold").fontSize(14).fillColor(COLORS.darkText)
      .text(`Already Completed (${completedTasks.length})`, 50);
    doc.moveDown(0.3);

    for (const task of completedTasks) {
      taskNumber++;
      drawTaskRow(doc, task, taskNumber, pageWidth, true);
    }
  }

  if (tasks.length === 0) {
    doc.moveDown(2);
    doc.font("Helvetica").fontSize(14).fillColor(COLORS.lightText)
      .text("No tasks scheduled for this day.", 50, doc.y, { align: "center", width: pageWidth });
    doc.moveDown(1);
    doc.fontSize(11)
      .text("Add tasks in AxTask and come back to print your checklist!", { align: "center", width: pageWidth });
  }

  doc.moveDown(1.5);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor(COLORS.border).lineWidth(0.5).stroke();
  doc.moveDown(0.5);

  doc.font("Helvetica-Bold").fontSize(11).fillColor(COLORS.darkText)
    .text("Notes / Additional Tasks:", 50);
  doc.moveDown(0.5);

  for (let i = 0; i < 6; i++) {
    const lineY = doc.y;
    if (lineY > 700) break;
    doc.rect(54, lineY + 2, 12, 12).strokeColor(COLORS.checkboxBorder).lineWidth(0.8).stroke();
    doc.moveTo(74, lineY + 14).lineTo(555, lineY + 14).strokeColor("#e5e7eb").lineWidth(0.5).stroke();
    doc.moveDown(1.2);
  }

  const bottomY = 742;
  doc.moveTo(50, bottomY - 20).lineTo(562, bottomY - 20).strokeColor(COLORS.border).lineWidth(0.5).stroke();
  doc.font("Helvetica").fontSize(8).fillColor(COLORS.lightText)
    .text(
      "Generated by AxTask • Take a photo of this completed checklist and upload it to update your tasks automatically",
      50, bottomY - 12, { align: "center", width: pageWidth }
    );

  return doc;
}

function drawTaskRow(doc: PDFKit.PDFDocument, task: Task, num: number, pageWidth: number, completed: boolean) {
  const startY = doc.y;

  if (startY > 680) {
    doc.addPage();
  }

  const y = doc.y;

  const boxX = 54;
  const boxSize = 14;
  doc.rect(boxX, y + 1, boxSize, boxSize)
    .strokeColor(COLORS.checkboxBorder)
    .lineWidth(0.8)
    .stroke();

  if (completed) {
    doc.moveTo(boxX + 3, y + 8).lineTo(boxX + 6, y + 12).lineTo(boxX + 11, y + 4)
      .strokeColor(COLORS.primary).lineWidth(1.5).stroke();
  }

  const textX = 78;
  const timeStr = task.time ? ` (${task.time})` : "";
  const numStr = `${num}. `;

  doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.lightText)
    .text(numStr, textX, y + 2, { continued: true });

  doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.darkText)
    .text(task.activity, { continued: false, width: pageWidth - 80 });

  if (timeStr) {
    doc.font("Helvetica").fontSize(8).fillColor(COLORS.mediumText)
      .text(timeStr, textX + doc.widthOfString(numStr + task.activity) + 4, y + 3);
    doc.y = y + 16;
  }

  const tagX = textX;
  const tagY = doc.y;

  doc.font("Helvetica").fontSize(8);

  const priorityColor = getPriorityColor(task.priority);
  doc.fillColor(priorityColor).text(`${task.priority}`, tagX, tagY, { continued: true });

  if (task.classification) {
    doc.fillColor(COLORS.lightText).text(` • ${task.classification}`, { continued: false });
  } else {
    doc.text("", { continued: false });
  }

  if (task.notes && task.notes.trim()) {
    const truncated = task.notes.length > 100 ? task.notes.slice(0, 100) + "…" : task.notes;
    doc.font("Helvetica").fontSize(8).fillColor(COLORS.mediumText)
      .text(`→ ${truncated}`, textX, doc.y, { width: pageWidth - 80 });
  }

  doc.moveDown(0.2);

  doc.moveTo(50, doc.y + 2).lineTo(562, doc.y + 2).strokeColor("#f3f4f6").lineWidth(0.5).stroke();
  doc.moveDown(0.5);
}
