import { PassThrough } from "node:stream";
import { finished } from "node:stream/promises";
import PDFDocument from "pdfkit";
import type { Task } from "@shared/schema";
import { AXTASK_BRAND, AXTASK_TAGLINE } from "@shared/attribution";

function formatWhen(d: Date | string | null | undefined): string {
  if (!d) return "—";
  try {
    const x = typeof d === "string" ? new Date(d) : d;
    return x.toISOString();
  } catch {
    return String(d);
  }
}

function buildTaskReportDoc(task: Task, userName?: string): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `${AXTASK_BRAND} Task Report — ${task.activity.slice(0, 80)}`,
      Author: AXTASK_BRAND,
      Subject: "Single task report",
      Keywords: `${AXTASK_BRAND}; ${AXTASK_TAGLINE}; task report`,
      Creator: AXTASK_BRAND,
      Producer: AXTASK_BRAND,
    },
  });

  const pageWidth = 612 - 100;
  const labelX = 50;
  const valueX = 200;

  doc.font("Helvetica-Bold").fontSize(20).fillColor("#1e40af")
    .text(`${AXTASK_BRAND} Task Report`, { align: "center", width: pageWidth });
  doc.moveDown(0.5);
  doc.font("Helvetica").fontSize(10).fillColor("#6b7280")
    .text(`Generated ${new Date().toISOString()}`, { align: "center", width: pageWidth });
  if (userName) {
    doc.moveDown(0.2).text(`For: ${userName}`, { align: "center", width: pageWidth });
  }
  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#d1d5db").lineWidth(1).stroke();
  doc.moveDown(0.8);

  const rows: [string, string][] = [
    ["Task ID", task.id],
    ["Date", task.date],
    ["Time", task.time || "—"],
    ["Activity", task.activity],
    ["Status", task.status],
    ["Priority", task.priority],
    ["Classification", task.classification],
    ["Notes", task.notes?.trim() ? task.notes : "—"],
    ["Urgency", task.urgency != null ? String(task.urgency) : "—"],
    ["Impact", task.impact != null ? String(task.impact) : "—"],
    ["Effort", task.effort != null ? String(task.effort) : "—"],
    ["Prerequisites", task.prerequisites?.trim() ? task.prerequisites : "—"],
    ["Recurrence", task.recurrence || "—"],
    ["Visibility", task.visibility],
    ["Created", formatWhen(task.createdAt)],
    ["Updated", formatWhen(task.updatedAt)],
  ];

  for (const [label, value] of rows) {
    if (doc.y > 720) {
      doc.addPage();
    }
    const y = doc.y;
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#4b5563").text(label, labelX, y, { width: 130 });
    doc.font("Helvetica").fontSize(10).fillColor("#111827").text(value, valueX, y, { width: pageWidth - (valueX - 50) });
    doc.moveDown(0.55);
  }

  doc.moveDown(1);
  doc.font("Helvetica").fontSize(8).fillColor("#9ca3af")
    .text(`Generated by ${AXTASK_BRAND} (${AXTASK_TAGLINE})`, 50, doc.y, { align: "center", width: pageWidth });

  return doc;
}

export async function generateTaskReportPdfBuffer(task: Task, userName?: string): Promise<Buffer> {
  const doc = buildTaskReportDoc(task, userName);
  const chunks: Buffer[] = [];
  const stream = new PassThrough();
  stream.on("data", (chunk: Buffer) => chunks.push(chunk));
  doc.pipe(stream);
  doc.end();
  await finished(stream);
  return Buffer.concat(chunks);
}
